In [36]:
import yfinance as yf
import pandas as pd
import numpy as np
import requests

from bs4 import BeautifulSoup
from io import StringIO

In [37]:
# stocks = [

#     # Technology
#     'AAPL','MSFT','NVDA','GOOG','META','AMZN','TSLA',
#     'AMD','INTC','CSCO','ORCL','CRM','ADBE','QCOM',
#     'TXN','AVGO','IBM','AMAT','MU','NOW',

#     # Banking & Finance
#     'JPM','BAC','WFC','GS','MS','C','AXP','BLK',
#     'SCHW','USB','PNC','TFC',

#     # Energy
#     'XOM','CVX','COP','SLB','EOG','PSX','MPC',

#     # Healthcare
#     'JNJ','PFE','MRK','ABBV','TMO','LLY','ABT',
#     'DHR','BMY','UNH','CVS',

#     # Consumer
#     'KO','PEP','PG','COST','WMT','HD','MCD',
#     'SBUX','NKE','LOW','TGT',

#     # Industrials
#     'CAT','BA','HON','GE','MMM','UPS','FDX',
#     'LMT','DE',

#     # Telecom & Media
#     'VZ','T','CMCSA','DIS','NFLX',

#     # Utilities
#     'NEE','DUK','SO',

#     # Real Estate
#     'AMT','PLD','SPG',

#     # Materials
#     'LIN','APD','FCX',

#     # Transportation
#     'UNP','CSX',

#     # Semiconductor
#     'NXPI','KLAC','LRCX',

#     # Additional large caps
#     'PYPL','UBER','SHOP','ZM'
# ]

In [38]:
url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

table = soup.find('table', {'id': 'constituents'})

sp500 = pd.read_html(
    StringIO(str(table))
)[0]

sp500.head()

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989

In [40]:
stocks = sp500['Symbol'].tolist()[:100]

stocks = [stock.replace('.', '-') for stock in stocks]

stocks[:100]

['MMM',
 'AOS',
 'ABT',
 'ABBV',
 'ACN',
 'ADBE',
 'AMD',
 'AES',
 'AFL',
 'A',
 'APD',
 'ABNB',
 'AKAM',
 'ALB',
 'ARE',
 'ALGN',
 'ALLE',
 'LNT',
 'ALL',
 'GOOGL',
 'GOOG',
 'MO',
 'AMZN',
 'AMCR',
 'AEE',
 'AEP',
 'AXP',
 'AIG',
 'AMT',
 'AWK',
 'AMP',
 'AME',
 'AMGN',
 'APH',
 'ADI',
 'AON',
 'APA',
 'APO',
 'AAPL',
 'AMAT',
 'APP',
 'APTV',
 'ACGL',
 'ADM',
 'ARES',
 'ANET',
 'AJG',
 'AIZ',
 'T',
 'ATO',
 'ADSK',
 'ADP',
 'AZO',
 'AVB',
 'AVY',
 'AXON',
 'BKR',
 'BALL',
 'BAC',
 'BAX',
 'BDX',
 'BRK-B',
 'BBY',
 'TECH',
 'BIIB',
 'BLK',
 'BX',
 'XYZ',
 'BNY',
 'BA',
 'BKNG',
 'BSX',
 'BMY',
 'AVGO',
 'BR',
 'BRO',
 'BF-B',
 'BLDR',
 'BG',
 'BXP',
 'CHRW',
 'CDNS',
 'CPT',
 'CPB',
 'COF',
 'CAH',
 'CCL',
 'CARR',
 'CVNA',
 'CASY',
 'CAT',
 'CBOE',
 'CBRE',
 'CDW',
 'COR',
 'CNC',
 'CNP',
 'CF',
 'CRL',
 'SCHW']

In [41]:
etfs = [
    'SPY','QQQ','DIA','IWM',
    'XLF','XLK','XLE','XLV',
    'XLY','XLP','XLI','XLU',
    'VNQ','GLD','TLT'
]

In [42]:
symbols = stocks + etfs

len(symbols)

115

In [43]:
start_date = '2018-01-01'

# Dynamic latest date
end_date = pd.Timestamp.today().strftime('%Y-%m-%d')

data = yf.download(
    symbols,
    start=start_date,
    end=end_date,
    auto_adjust=False
)

[*********************100%***********************]  115 of 115 completed

In [44]:
adj_close = data['Adj Close']

adj_close.head()

Ticker,A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,...,VNQ,XLE,XLF,XLI,XLK,XLP,XLU,XLV,XLY,XYZ
2018-01-02,63.522755,40.267078,68.773163,NaN,50.506077,27.988113,135.558228,177.699997,77.602303,31.201908,...,60.170986,25.747255,23.884138,66.254860,29.872921,45.314568,20.132580,72.723320,46.275238,36.169998
2018-01-03,65.139046,40.260075,69.849350,NaN,50.617756,28.013470,136.183899,181.039993,78.565018,30.960634,...,59.996296,26.132862,24.012459,66.611702,30.122099,45.298538,19.974426,73.419174,46.487698,37.310001
2018-01-04,64.650383,40.447071,69.451019,NaN,50.531857,28.118069,137.796432,183.220001,78.479042,31.482090,...,58.962772,26.290606,24.234877,67.099121,30.274372,45.426769,19.808550,73.523552,46.640133,38.099998
2018-01-05,65.684067,40.907574,70.660027,NaN,50.677906,28.007132,138.933105,185.339996,78.797104,31.271946,...,58.991871,26.280090,24.303310,67.560432,30.592754,45.627136,19.800829,74.149803,47.009617,41.139999
2018-01-08,65.824997,40.755638,69.527901,NaN,50.531857,28.010302,140.043381,185.039993,78.934639,31.201908,...,59.297569,26.437830,24.269096,67.838974,30.708120,45.739342,19.985994,73.880188,47.065037,40.759998

In [45]:
print("Expected Symbols:", len(symbols))

print("Downloaded Symbols:", len(adj_close.columns))

missing_symbols = set(symbols) - set(adj_close.columns)

print("Missing Symbols:")

print(missing_symbols)

Expected Symbols: 115
Downloaded Symbols: 115
Missing Symbols:
set()

In [46]:
adj_close.index = pd.to_datetime(adj_close.index)

adj_close.index

DatetimeIndex(['2018-01-02', '2018-01-03', '2018-01-04', '2018-01-05',
               '2018-01-08', '2018-01-09', '2018-01-10', '2018-01-11',
               '2018-01-12', '2018-01-16',
               ...
               '2026-05-11', '2026-05-12', '2026-05-13', '2026-05-14',
               '2026-05-15', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22'],
              dtype='datetime64[s]', length=2109, freq=None)

In [47]:
print(
    "Duplicate Dates:",
    adj_close.index.duplicated().sum()
)

adj_close = adj_close[
    ~adj_close.index.duplicated()
]

Duplicate Dates: 0

In [48]:
adj_close.isnull().sum()

Ticker
A         0
AAPL      0
ABBV      0
ABNB    741
ABT       0
       ...
XLP       0
XLU       0
XLV       0
XLY       0
XYZ       0
Length: 115, dtype: int64

In [49]:
missing_pct = (
    adj_close.isnull().mean() * 100
)

missing_pct.sort_values(
    ascending=False
)

Ticker
APP     39.165481
ABNB    35.135135
CARR    26.363205
A        0.000000
CNP      0.000000
          ...
APA      0.000000
AOS      0.000000
AON      0.000000
ANET     0.000000
XYZ      0.000000
Length: 115, dtype: float64

In [50]:
valid_cols = missing_pct[
    missing_pct < 5
].index

adj_close = adj_close[valid_cols]

In [51]:
adj_close = adj_close.ffill().bfill()

In [52]:
adj_close.isnull().sum().sum()

0

In [53]:
(adj_close <= 0).sum().sum()

0

In [54]:
adj_close.to_csv(
    '../data/cleaned/adj_close_cleaned.csv'
)

In [55]:
returns = adj_close.pct_change().dropna()

returns.head()

Ticker,A,AAPL,ABBV,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP,...,VNQ,XLE,XLF,XLI,XLK,XLP,XLU,XLV,XLY,XYZ
2018-01-03,0.025444,-0.000174,0.015648,0.002211,0.000906,0.004616,0.018796,0.012406,-0.007733,0.010863,...,-0.002903,0.014977,0.005373,0.005386,0.008341,-0.000354,-0.007856,0.009569,0.004591,0.031518
2018-01-04,-0.007502,0.004645,-0.005703,-0.001697,0.003734,0.011841,0.012042,-0.001094,0.016843,0.009552,...,-0.017226,0.006036,0.009263,0.007317,0.005055,0.002831,-0.008304,0.001422,0.003279,0.021174
2018-01-05,0.015989,0.011385,0.017408,0.002890,-0.003945,0.008249,0.011571,0.004053,-0.006675,-0.000591,...,0.000494,-0.000400,0.002824,0.006875,0.010517,0.004411,-0.000390,0.008518,0.007922,0.079790
2018-01-08,0.002146,-0.003714,-0.016022,-0.002882,0.000113,0.007991,-0.001619,0.001745,-0.002240,-0.003044,...,0.005182,0.006002,-0.001408,0.004123,0.003771,0.002459,0.009351,-0.003636,0.001179,-0.009237
2018-01-09,0.024554,-0.000115,0.007538,0.001700,-0.012900,0.003335,0.008971,-0.002069,0.003243,0.006953,...,-0.012888,-0.002519,0.007754,0.006415,-0.002555,-0.001402,-0.009843,0.011773,0.001963,0.002944

In [56]:
log_returns = np.log(
    adj_close / adj_close.shift(1)
).dropna()

In [57]:
normalized_prices = (
    adj_close / adj_close.iloc[0]
)

normalized_prices.head()

Ticker,A,AAPL,ABBV,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP,...,VNQ,XLE,XLF,XLI,XLK,XLP,XLU,XLV,XLY,XYZ
2018-01-02,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
2018-01-03,1.025444,0.999826,1.015648,1.002211,1.000906,1.004616,1.018796,1.012406,0.992267,1.010863,...,0.997097,1.014977,1.005373,1.005386,1.008341,0.999646,0.992144,1.009569,1.004591,1.031518
2018-01-04,1.017752,1.004470,1.009856,1.000510,1.004643,1.016511,1.031064,1.011298,1.008980,1.020519,...,0.979920,1.021103,1.014685,1.012743,1.013439,1.002476,0.983905,1.011004,1.007885,1.053359
2018-01-05,1.034024,1.015906,1.027436,1.003402,1.000680,1.024896,1.042994,1.015396,1.002245,1.019916,...,0.980404,1.020695,1.017550,1.019705,1.024097,1.006898,0.983522,1.019615,1.015870,1.137407
2018-01-08,1.036243,1.012133,1.010974,1.000510,1.000793,1.033087,1.041306,1.017169,1.000000,1.016812,...,0.985484,1.026821,1.016118,1.023909,1.027958,1.009374,0.992719,1.015908,1.017067,1.126901

In [58]:
normalized_prices.to_csv(
    '../data/processed/normalized_prices.csv'
)

In [59]:
rolling_volatility = (
    returns.rolling(30).std()
)

rolling_volatility.head()

Ticker,A,AAPL,ABBV,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP,...,VNQ,XLE,XLF,XLI,XLK,XLP,XLU,XLV,XLY,XYZ
2018-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
rolling_volatility.to_csv(
    '../data/processed/rolling_volatility.csv'
)

In [61]:
returns.to_csv(
    '../data/processed/returns.csv'
)

log_returns.to_csv(
    '../data/processed/log_returns.csv'
)

In [62]:
returns.describe()

Ticker,A,AAPL,ABBV,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP,...,VNQ,XLE,XLF,XLI,XLK,XLP,XLU,XLV,XLY,XYZ
count,2108.000000,2108.000000,2108.000000,2108.000000,2108.000000,2108.000000,2108.000000,2108.000000,2108.000000,2108.000000,...,2108.000000,2108.000000,2108.000000,2108.000000,2108.000000,2108.000000,2108.000000,2108.000000,2108.000000,2108.000000
mean,0.000449,0.001151,0.000685,0.000381,0.000757,0.000291,0.000413,0.001008,0.000589,0.000528,...,0.000322,0.000596,0.000477,0.000542,0.000990,0.000345,0.000467,0.000403,0.000560,0.001008
std,0.018271,0.019220,0.016821,0.015558,0.018436,0.017825,0.022735,0.021604,0.017560,0.016014,...,0.013806,0.019827,0.014696,0.013410,0.016522,0.009804,0.012757,0.010976,0.014904,0.037539
min,-0.110117,-0.128647,-0.162524,-0.100389,-0.168752,-0.095881,-0.167932,-0.166149,-0.241971,-0.152526,...,-0.177277,-0.201412,-0.137093,-0.113442,-0.138140,-0.093956,-0.113577,-0.098610,-0.126686,-0.285615
25%,-0.008783,-0.007833,-0.007053,-0.007017,-0.007444,-0.007688,-0.009936,-0.010254,-0.007583,-0.006485,...,-0.006056,-0.008869,-0.005888,-0.005553,-0.007096,-0.004274,-0.005872,-0.004970,-0.006418,-0.018755
50%,0.000887,0.001176,0.001108,0.000686,0.001242,0.001090,0.001133,0.001183,0.000943,0.001170,...,0.000789,0.001036,0.000846,0.000970,0.001738,0.000557,0.001028,0.000571,0.001327,0.001367
75%,0.010168,0.010930,0.009150,0.008588,0.009826,0.009101,0.012255,0.012569,0.009636,0.008315,...,0.007232,0.010251,0.007512,0.007314,0.009787,0.005355,0.006972,0.006024,0.008446,0.020240
max,0.098394,0.153289,0.137673,0.109360,0.153577,0.128573,0.177193,0.183876,0.102695,0.118036,...,0.089967,0.160373,0.131566,0.126512,0.134257,0.085106,0.127934,0.077057,0.108880,0.261396

In [63]:
returns.corr()

Ticker,A,AAPL,ABBV,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP,...,VNQ,XLE,XLF,XLI,XLK,XLP,XLU,XLV,XLY,XYZ
Ticker,,,,,,,,,,,,,,,,,,,,,
A,1.000000,0.480561,0.358536,0.515574,0.355905,0.529698,0.470779,0.536553,0.338805,0.481002,...,0.519647,0.347227,0.544160,0.598498,0.602320,0.465426,0.390998,0.686000,0.585676,0.456418
AAPL,0.480561,1.000000,0.279444,0.428957,0.332750,0.520852,0.574756,0.580393,0.311703,0.504093,...,0.498243,0.347984,0.540393,0.582299,0.812722,0.491938,0.353332,0.554332,0.693787,0.498192
ABBV,0.358536,0.279444,1.000000,0.408343,0.322467,0.319504,0.255944,0.275650,0.266238,0.358520,...,0.369014,0.319679,0.395716,0.394439,0.326145,0.437196,0.323092,0.628685,0.300915,0.177297
ABT,0.515574,0.428957,0.408343,1.000000,0.377234,0.470083,0.408281,0.397688,0.317010,0.505970,...,0.495660,0.255812,0.485564,0.500741,0.481750,0.564230,0.472624,0.722945,0.445430,0.340674
ACGL,0.355905,0.332750,0.322467,0.377234,1.000000,0.441511,0.281590,0.364385,0.434009,0.535089,...,0.565781,0.495129,0.690474,0.623155,0.400080,0.529918,0.507327,0.535149,0.449668,0.252968
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XLP,0.465426,0.491938,0.437196,0.564230,0.529918,0.507282,0.385749,0.423671,0.530392,0.589484,...,0.680720,0.401123,0.614879,0.643287,0.508887,1.000000,0.699332,0.720346,0.547704,0.285858
XLU,0.390998,0.353332,0.323092,0.472624,0.507327,0.394021,0.248232,0.326646,0.427350,0.517298,...,0.732410,0.372026,0.528966,0.571583,0.420108,0.699332,1.000000,0.593691,0.436848,0.270099
XLV,0.686000,0.554332,0.628685,0.722945,0.535149,0.600028,0.497717,0.551983,0.456260,0.635511,...,0.667326,0.453491,0.681217,0.711945,0.649161,0.720346,0.593691,1.000000,0.628460,0.430246
XLY,0.585676,0.693787,0.300915,0.445430,0.449668,0.628731,0.620789,0.679661,0.395424,0.597967,...,0.663103,0.461104,0.725578,0.773131,0.834820,0.547704,0.436848,0.628460,1.000000,0.661327
XYZ,0.456418,0.498192,0.177297,0.340674,0.252968,0.471026,0.536693,0.488769,0.210370,0.434743,...,0.453583,0.287998,0.469806,0.501801,0.627774,0.285858,0.270099,0.430246,0.661327,1.000000

In [64]:
returns.max()

returns.min()

Ticker
A      -0.110117
AAPL   -0.128647
ABBV   -0.162524
ABT    -0.100389
ACGL   -0.168752
          ...
XLP    -0.093956
XLU    -0.113577
XLV    -0.098610
XLY    -0.126686
XYZ    -0.285615
Length: 112, dtype: float64

In [65]:
print("FINAL DATASET SUMMARY")

print("-" * 40)

print(
    "Number of Assets:",
    adj_close.shape[1]
)

print(
    "Trading Days:",
    adj_close.shape[0]
)

print(
    "Start Date:",
    adj_close.index.min()
)

print(
    "End Date:",
    adj_close.index.max()
)

print(
    "Remaining Missing Values:",
    adj_close.isnull().sum().sum()
)

FINAL DATASET SUMMARY
----------------------------------------
Number of Assets: 112
Trading Days: 2109
Start Date: 2018-01-02 00:00:00
End Date: 2026-05-22 00:00:00
Remaining Missing Values: 0